// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using OrderAPI.Entities;

namespace OrderAPI.Entities;

[Index("OrderId", Name = "UQ__Payments__C3905BCE09EA9972", IsUnique = true)]
public partial class Payment
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Required]
    [StringLength(50)]
    public string Method { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Payment")]
    public virtual Order Order { get; set; }
}