name: orderapi

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: backend_sql_server
    restart: unless-stopped
    ports:
      - "9999:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password2026
    volumes:
      - mssql_data:/var/opt/mssql

    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password2026", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Tái sử dụng file DataSeed.sql để tự động dựng DB cho Docker
  database-seed:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: backend_sql_seed
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./database_seed:/usr/src/database_seed # Map thư mục chứa file SQL của bạn vào container
    entrypoint: >
      /bin/bash -c "
      echo '=== [Docker-Init] Đang tiến hành chạy file DataSeed.sql để khởi tạo cấu trúc... ===';
      /opt/mssql-tools18/bin/sqlcmd -S database -U sa -P YourStrong@Password2026 -C -i /usr/src/database_seed/DataSeed.sql;
      echo '=== [Docker-Init] Hoàn thành import cấu trúc và dữ liệu mẫu thành công! ===';
      "

  app:
    build:
      context: ./OrderAPI
      dockerfile: Dockerfile
    container_name: backend_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=database;Database=BackendLearningDB;User Id=sa;Password=YourStrong@Password2026;TrustServerCertificate=True;
      - JwtSettings__SecretKey=SuperSecretKeyForSalesAndOrderManagementAPI2026
      - JwtSettings__Issuer=SalesOrderAPI
      - JwtSettings__Audience=SalesOrderClient
      - JwtSettings__AccessTokenExpiryMinutes=15
      - JwtSettings__RefreshTokenExpiryDays=7
    depends_on:
      database:
        condition: service_healthy

volumes:
  mssql_data:
    name: orderapi_mssql_data